apiVersion: v1
kind: Service
metadata:
  labels:
    app: lyle-dev-web
  name: lyle-dev-web
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: lyle-dev-web