apiVersion: v1
kind: Service
metadata:
  name: lyle-dev
  labels:
    app: lyle-dev
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 31111
  selector:
    app: lyle-dev
